image: gradle:alpine

cache:
  paths:
    - .gradle

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
  tags:
    - build
