Setting:
  serverName: "xxx"
  mysql:
    enable: false
    url: "localhost"
    user: "root"
    port: 3306
    password: "root"
    database: "test"
  redis:
    enable: false
    url: "localhost"
    port: 6379
    maxTotal: 20
    maxIdle: 10
    minIdle: 1
    maxWaitMillis: 60000
    testOnBorrow: true
    testOnReturn: true