server-name: "xxx"
mysql:
  enable: false
  url: "localhost"
  user: "root"
  port: 3306
  password: "root"
  database: "test"
redis:
  enable: false
  url: "localhost"
  port: 6379
  max-total: 20
  max-idle: 10
  min-idle: 1
  max-wait-millis: 60000
  test-on-borrow: true
  test-on-return: true
skull-save-time: 10